Repository YatopiaMC/Yatopia, pull requests merged in 2021-02, with the labels that each got.

#371 Merge staging/1.16.5
  .github/workflows/build.yml
  Jenkinsfile
  PATCHES.md
  Yatoclip/build.gradle.kts
  Yatoclip/src/java9/java/org/yatopiamc/yatoclip/YatoclipLaunch.java
  Yatoclip/src/main/java/org/yatopiamc/yatoclip/PatchesMetadata.java
  Yatoclip/src/main/java/org/yatopiamc/yatoclip/ServerSetup.java
  Yatoclip/src/main/java/org/yatopiamc/yatoclip/SpecialSourceLauncher.java
  Yatoclip/src/main/java/org/yatopiamc/yatoclip/Yatoclip.java
  Yatoclip/src/main/java/org/yatopiamc/yatoclip/YatoclipLaunch.java
  Yatoclip/src/main/java/org/yatopiamc/yatoclip/YatoclipPatcher.java
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/yatopiamc/yatoclip/gradle/MakePatchesTask.java
  buildSrc/src/main/java/org/yatopiamc/yatoclip/gradle/PatchesMetadata.java
  buildSrc/src/main/java/org/yatopiamc/yatoclip/gradle/PropertiesUtils.java
  buildSrc/src/main/kotlin/ConfigureSubprojects.kt
  buildSrc/src/main/kotlin/DependencyLoading.kt
  buildSrc/src/main/kotlin/ToothpickExtension.kt
  buildSrc/src/main/kotlin/ToothpickExtensions.kt
  buildSrc/src/main/kotlin/task/RebuildPatches.kt
  patches/api/0008-Suspected-plugins-report.patch
  patches/removed/server/0060-New-Network-System.patch
  patches/server/0001-Modify-POM.patch
  patches/server/0002-Brandings.patch
  patches/server/0003-Utilities.patch
  patches/server/0009-Add-NBT-API-as-a-first-class-lib.patch
  patches/server/0062-lithium-cache-chunk-gen-sea-level.patch
  patches/server/0063-PaperPR-Inline-shift-direction-fields.patch
  patches/server/0064-New-nbt-cache.patch
  patches/server/0065-Suspected-plugins-report.patch
  settings.gradle.kts
  subprojects/server.gradle.kts
Labels: enhancement, normal priority

#396 Drop MyPet fix
  PATCHES.md
  patches/server/0065-Fix-NPE-in-ControllerLookWASD-and-ControllerMoveWASD.patch
Labels: normal priority

#383 Cadmium + LazyDFU port
  Licensing/LICENSE.md
  PATCHES.md
  README.md
  buildSrc/src/main/kotlin/MCDevImports.kt
  patches/server/0066-Port-Cadmium.patch
  patches/server/0067-Port-LazyDFU.patch
Labels: Ready for Review
